import mongoose from "mongoose"

const VisitorSchema = new mongoose.Schema(
  {
    visitorId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },
    sessionId: String,
    timestamp: Number,
    page: String,
    referrer: String,
    userAgent: String,
    language: String,
    timezone: String,
    screenResolution: String,
    viewportSize: String,
    colorScheme: String,
    deviceType: String,
    platform: String,
    browser: String,
    browserVersion: String,
    os: String,
    osVersion: String,
    utmSource: String,
    utmMedium: String,
    utmCampaign: String,
    utmContent: String,
    utmTerm: String,
    gclid: String,
    fbclid: String,
    msclkid: String,
    connectionType: String,
    effectiveType: String,
    downlink: Number,
    rtt: Number,
    saveData: Boolean,
    memory: Number,
    cores: Number,
    hardwareConcurrency: Number,
    maxTouchPoints: Number,
    isOnline: Boolean,
    documentTitle: String,
    documentCharset: String,
    cookiesEnabled: Boolean,
    doNotTrack: String,
    plugins: [String],
    scrollDepth: Number,
    mouseMovements: Number,
    keyPresses: Number,
    clicks: Number,
    interactions: [String],
    lastUpdated: {
      type: Date,
      default: Date.now,
    },
  },
  { timestamps: true },
)

export const Visitor = mongoose.models?.Visitor || mongoose.model("Visitor", VisitorSchema)
